version: '3'

services:
  integrator-scheduler:
    image: pdh-integrator-scheduler
     build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - scheduler-network

networks:
  scheduler-network:
    name: scheduler-network
    external: true